server.port=${PORT:8080}
jwt.secret=${jwt.secret:mySecretKeyForMediConnectApp2024VeryLongAndSecure}
jwt.expiration=${jwt.expiration:86400000}
spring.datasource.url=${spring.datasource.url:jdbc:postgresql://localhost:5432/mediconnect_db}
spring.datasource.username=${spring.datasource.username:postgres}
spring.datasource.password=${spring.datasource.password:@Keerthana2003}
spring.jpa.hibernate.ddl-auto=update
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${spring.mail.username:ankeerthana2003@gmail.com}
spring.mail.password=${spring.mail.password:kzib decn xjhk vhln}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html